### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by NikodemMarek** [2024-2025-AGH-Wstep-do-Informatyki/python#2]
Proponuję żeby projekt używał SQLowej bazy danych, o strukturze:

```sql
CREATE TABLE Logs (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    ip INET NOT NULL,
    event_type TEXT NOT NULL, -- np. "failed_login", "too_many_requests"
    raw_event TEXT NOT NULL -- możliwe że się nie przyda
);

CREATE INDEX idx_logs_ip_timestamp ON Logs (ip, timestamp);
```

```sql
CREATE TABLE BlockedIPs (
    id SERIAL PRIMARY KEY,
    ip INET NOT NULL UNIQUE,
    block_time TIMESTAMP NOT NULL DEFAULT NOW(),
    unblock_time TIMESTAMP,
    reason TEXT NOT NULL
);

CREATE INDEX idx_blockedips_ip ON BlockedIPs (ip);
```

Dodatkowo można by dodać tabelę która agreguje logi (np. do wyświetlania statystyk):

```sql
CREATE TABLE AggregatedLogs (
    id SERIAL PRIMARY KEY,
    ip INET NOT NULL,
    event_type TEXT NOT NULL,
    event_count INT NOT NULL,
    start TIMESTAMP NOT NULL,
    end TIMESTAMP NOT NULL
);

CREATE INDEX idx_aggregatedlogs_ip ON AggregatedLogs (ip);
```

Baza danych którą proponuje to SQLite, ponieważ jest prosta i wbudowana w pythona.

**Comment by NikodemMarek** [comment]
nie wiem czy postgres nie będzie przesadą, można te inety zrobić po prostu jako varchary

**Comment by Plasny** [comment]
good idea, ale może trzymajmy się tego nazewnictwa najbardziej basicowego i dajmy to jako TEXT, bo to w sumie to samo co VARCHAR

**Comment by NikodemMarek** [comment]
blockedips nie będzie miało unique na ip, bo chcemy mieć dane o wszystkich blockach i nublockach, nie tylko ostatnich
